### ISSUE TITLE
docs/CHANGELIST.md file is missing in master branch

### ISSUE THREAD

**Issue by avosdewael** [Azure/azure-kusto-spark#107]
**Describe the bug**
In the master branch head (commit 1f3a054), the Readme refers to a changelist. For example: `For main changes from previous releases and known issues please refer to [CHANGELIST](docs/CHANGELIST.md)`

However, this referenced `docs/CHANGELIST.md` file is not available in the master branch.

**To Reproduce**
1. In a webbrowser, open the repository homepage at https://github.com/Azure/azure-kusto-spark
2. In the rendered Readme markdown text, click on the first 'CHANGELIST' hyperlink. This redirects the browser to https://github.com/Azure/azure-kusto-spark/blob/master/docs/CHANGELIST.md, which returns a Github 404 error page.

**Expected behavior**
I expect the changelist to be available in the master branch.

Could you please look into this? Thanks in advance.

**Comment by ohadbitt** [comment]
Sorry foe not seeing this
Changelist is not used anymore
Refer to the repo releases and look at the changes
