### ISSUE TITLE
Question: PySpark connector without using an AAD app

### ISSUE THREAD

**Issue by JulesBelveze** [Azure/azure-kusto-spark#110]
Hi guys,

I am currently using DataBricks and trying to set up a PySpark connect without using an Azure AD application. 
I was looking at the provided examples in PySpark but they all require an `AAD_CLIENT_ID`. I was wondering whether or not there is a way not to use any application?
Thank you for your help!

**Comment by ohadbitt** [comment]
There is no difference between what u can do with  pySpark and scala.. simply use the right option for what u need
Which authentication method are you trying to do?

**Comment by JulesBelveze** [comment]
I am trying to use the one with [Direct Authentication With Access Token](https://github.com/Azure/azure-kusto-spark/blob/master/docs/Authentication.md#direct-authentication-with-access-token).

**Comment by ohadbitt** [comment]
Add an option with key
"accessToken"
And value is your token

**Comment by JulesBelveze** [comment]
Hmm ok thank you for your help! I'll try to figure it out :)

**Comment by ohadbitt** [comment]
Device auth for pyspark has been made easier in version 1.1.4.
please refer to the python sample
