### ISSUE TITLE
Provide capability of adding tags based on column while ingesting into kusto

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-kusto-spark#119]
As of today, KUSTO_SPARK_INGESTION_PROPERTIES_JSON allows to set tags like ingest-by and drop-by tags. By setting static value, all the rows gets inserted with same tags. There should a way to take column name part of Dataframe and tag row dynamically. 

Like if my data-frame has column with Date, by taking "Date" column value and tag it. 

 Today after inserting data with static value, again i have run alter command to re-tag with different value.

Since Kusto sink is using foreachwriter, you should be able to read column value and set tag before sending to blob.

**Comment by ohadbitt** [comment]
Decided this is not the connector's job to do it
It can be done by the client
