### ISSUE TITLE
Is there a way to run commands like '.show/.move/.drop' via Spart connector? 

### ISSUE THREAD

**Issue by MinKPark** [Azure/azure-kusto-spark#122]
Is there a way to run commands like '.show/.move/.drop' via Spark connector? 

I tried to do it via _pyKusto.read.option(Query,'.show table xxxx'). but it fails. 
I wonder whether there is a way to do it.

**Comment by ohadbitt** [comment]
commands are not supported through the connector 
please use the java client which the connector relies on
