### ISSUE TITLE
Correlate RunID/Data lineage ID between spark streaming and kusto

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-kusto-spark#127]
Spark Kusto sync connector works fine in copying data from streaming to Kusto. If there are multiple spark streaming job which sinks to single table. There is no way to traces or links from which stream data has got inserted. We are looking for a way to detect the source stream . In other words, we have streaming job which emits Raw data like ID, Run ID or Reservoir ID, Can we have these IDs tracked in kusto commands like .show commands or .show operations during ingestion process. So we need lineage ID 

**Streaming Job Raw Data**
"id" : "12e0721e-5ddb-4d98-bbcf-ef1409b10201",
  "runId" : "aef8916f-fe50-4156-9473-e16435f2d8ec",
 "reservoirId" : "40ec0b33-a2a6-4a40-8c62-6eebbaf81699",

**Comment by vladikbr** [comment]
No, you cannot add custom data to be present in Kusto .show commands output.
You can use Extent tagging to "mark" your data: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/extents-overview#extent-tagging
