### ISSUE TITLE
Handling Transient Failures during ingestion.

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-kusto-spark#128]
Once in a while, we are seeing transient failure during ingestion. Is there be retry performed for transient issue.

**_Reason for failure  : The client could not finish the operation within specified timeout.: : : - Transient_**

 .**_**show ingestion  failures| where OperationId == "56672f28-11ee-42a7-a13a-eaa2d75295a3"**_**

**Another Issue**:  As per current design, Spark Kusto Sink copy batch of records into temporary blob storage in .CSV.GZ format. Temporary Table is created point to temporary blob location. Finally move extents to target table. 

If streaming job is stopped, If there are any pending ingestion i.e Copying of temporary table to target table. Currently system stops copying data to Final Kusto Table. If spark checkpoint gets committed with batch of records read by streaming engine but  didn't/fail to copy data into target table. There is chance of Data loss. How exactly this scenario is handled.

**Comment by ohadbitt** [comment]
For the first:
For now - we implemented retries only on the polling of operation status 
https://github.com/Azure/azure-kusto-spark/pull/148 
For the second : 
We can't support it, if the connector is shutdown abruptly no more code will be activated, user can look for staging tables (prefixed : "_tmp") and merge them to the right destination (destination is part of the name )
