### ISSUE TITLE
Release for Scala 2.12

### ISSUE THREAD

**Issue by n3pheddy** [Azure/azure-kusto-spark#150]
**Is your feature request related to a problem? Please describe.**
Databricks 7.0+ is using Scala 2.12. The current kusto-spark-connector is built against Scala 2.11. Thus, it cannot be used with the most recent versions of Databricks. The most recent version of Databricks is 7.3 Beta at the time of this writing.

**Describe the solution you'd like**
Build for Scala 2.12 as well.

**Describe alternatives you've considered**
I could pull down the source code and build it manually, however, it only solves my issue and not for the community as a whole.

**Additional context**
When I tried to run Spark with the Connector installed, I get the following:

```
Py4JJavaError: An error occurred while calling o2145.start.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.microsoft.kusto.spark.datasink.WriteOptions.<init>(KustoSinkOptions.scala:43)
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$.parseSinkParameters(KustoDataSourceUtils.scala:207)
	at com.microsoft.kusto.spark.datasink.KustoSinkProvider.createSink(KustoSinkProvider.scala:17)
	at org.apache.spark.sql.execution.datasources.DataSource.createSink(DataSource.scala:325)
```

**Comment by ohadbitt** [comment]
Scala 12 will be released with support for spark 3.0.0 in the next week or so
do you need scala 12 for a lesser spark version?

**Comment by n3pheddy** [comment]
No, that will be perfect.

In my case I'm looking forward to use Auto Loader in Azure Databricks 7.2 (Scala 2.12, Spark 3.0.0) to stream data from a Storage Account to Data Explorer.

**Comment by ohadbitt** [comment]
Released a new artifact targeting the scala 12 and spark 3
3.0_v2.3.0
