### ISSUE TITLE
Data loss for async write with checkpointing enabled

### ISSUE THREAD

**Issue by mosaikia** [Azure/azure-kusto-spark#151]
We have a data pipeline where we ingest data from Azure Event Hub and after processing, write the data to Kusto. We are using Spark structured streaming with **spark version 2.4** and **scala version 2.11**. Also, we are writing to Kusto asynchronously and have checkpointing enabled for the SparkSession.

Our pom dependency for the kusto library used is:
```xml
<dependency>
<groupId>com.microsoft.azure.kusto</groupId>
<artifactId>spark-kusto-connector</artifactId>
<version>1.1.2</version>
</dependency>
```

The issue we are having is that if the job fails and restarts we see that the eventhub uses checkpointing to resume from the offsets till which it had last processed; but on the Kusto side we still end up losing data. It would be helpful if I could get some insight into the process so that we can solve the data loss issue.

**Comment by ohadbitt** [comment]
Hey 
checkpointing will not work for you properly in async mode. Async mode is a 'send and forget' kind of pipeline as processing continues without waiting for the ingestion to succeed. To get this sort of behavior with async you should somehow stop the stream source while letting a few minutes for the kusto stream to finish processing everything it queued asyncly
