### ISSUE TITLE
Are there more option to support overwrite while saving records into Kusto.

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-kusto-spark#162]
**Is your feature request related to a problem? Please describe.**
We are running Spark Job which reads batch of data from blob storage. We use SaveMode enum for writing data into Kusto.
This works for transaction/Log data. But in the case of master data loading, we would like to Wipe out existing data and refresh table with new set of master data. Currently we see only "SaveMode.Append" is supported. Is there any option of SaveMode.Overwite to replace with new data

val async = false;
var finalDF= spark.sql("SELECT * FROM workspaces")

val kustoQ = finalDF.write
      .format("com.microsoft.kusto.spark.datasource")
      .option(KustoSinkOptions.KUSTO_CLUSTER, kustoCluster)
      .option(KustoSinkOptions.KUSTO_DATABASE, kustoDatabase)
      .option(KustoSinkOptions.KUSTO_TABLE, kustoTargetTable)
      .option(KustoSinkOptions.KUSTO_AAD_CLIENT_ID, kustoAADAppID)
      .option(KustoSinkOptions.KUSTO_AAD_CLIENT_PASSWORD, kustoSecretKey)
      .option(KustoSinkOptions.KUSTO_TABLE_CREATE_OPTIONS, "CreateIfNotExist")
      .option(KustoSinkOptions.KUSTO_WRITE_ENABLE_ASYNC, async)
      .mode(SaveMode.Append)
      .save()

**Comment by ohadbitt** [comment]
Hi, 
To replace existing data please use tags and the replace command
Tags usage in the connector:
https://github.com/Azure/azure-kusto-spark/blob/8c597932324680aa24e77cc5eaef40b118be7324/samples/src/main/python/pyKusto.py#L89
Tags example to replace data: 
https://yonileibowitz.github.io/kusto.blog/blog-posts/advanced-data-management.html#tagging-and-replacing-extents-data-shards

**Comment by aayushsin** [comment]
@ohadbitt Can you please share a working example to overwrite the data using tags? The link does not seem to be working anymore
