### ISSUE TITLE
overwrite doesn't work for python

### ISSUE THREAD

**Issue by replyxf** [Azure/azure-kusto-spark#166]
Overwrite doesn't work for python, Append works. Can you please check?
    .mode('Overwrite') \
10
    .save()
java.security.InvalidParameterException: Kusto data source supports only &#39;Append&#39; mode, &#39;Overwrite&#39; directive is invalid. Please use df.write.mode(SaveMode.Append).

**Comment by ohadbitt** [comment]
As the error states we dont support 'Overwrite' SaveMode out of the box .
Overwrite in kusto can be done using extents tags 
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/replace-extents
In the connector tags can be supplied using the option KustoSinkOptions.KUSTO_SPARK_INGESTION_PROPERTIES_JSON
https://github.com/Azure/azure-kusto-spark/blob/master/docs/KustoSink.md
