### ISSUE TITLE
getClusterNameFromUrlIfNeeded fails on valid URL

### ISSUE THREAD

**Issue by dciborow** [Azure/azure-kusto-spark#169]
**Describe the bug**
I am trying to connect to my PlayFab Data Explorer, which has a cluster URL, "https://insights.playfab.com"
Per the directions here
https://docs.microsoft.com/en-us/gaming/playfab/features/insights/connectivity/connecting-kusto-explorer-to-insights
the URL should not be modified.

**To Reproduce**
from pyspark.sql import SparkSession

pyKusto = SparkSession.builder.appName("kustoPySpark").getOrCreate()

kustoOptions = {
  "kustoCluster":"https://insights.playfab.com",
  "kustoDatabase" : "912A9",
  "kustoTable" : "events.all",
  "kustoAadAppId":"" ,
  "kustoAadAppSecret":"",
  "kustoAadAuthorityID":""
}

# Read the data from the kusto table with default reading mode
kustoDf  = pyKusto.read. \
            format("com.microsoft.kusto.spark.datasource"). \
            option("kustoCluster", kustoOptions["kustoCluster"]). \
            option("kustoDatabase", kustoOptions["kustoDatabase"]). \
            option("kustoQuery", kustoOptions["kustoTable"]). \
            option("kustoAadAppId", kustoOptions["kustoAadAppId"]). \
            option("kustoAadAppSecret", kustoOptions["kustoAadAppSecret"]). \
            option("kustoAadAuthorityID", kustoOptions["kustoAadAuthorityID"]). \
            load()

Py4JJavaError: An error occurred while calling o521.load.
: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$.getClusterNameFromUrlIfNeeded(KustoDataSourceUtils.scala:270)
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$.parseSourceParameters(KustoDataSourceUtils.scala:107)
	at com.microsoft.kusto.spark.datasource.DefaultSource.createRelation(DefaultSource.scala:88)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:387)

**Expected behavior**

The string should not be processed how ever its being processed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9027725/107731707-a1ddf580-6cc4-11eb-93dd-a2c1ec00e063.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu, Spark on Databricks

**Comment by dciborow** [comment]
This is around the code thats failing.
![image](https://user-images.githubusercontent.com/9027725/107732134-9b9c4900-6cc5-11eb-9f3b-5252b90b6649.png)

**Comment by ohadbitt** [comment]
It doesnt seem like this is the cluster url .. it should be the same url you would use to connect to it via the UI 
https://dataexplorer.azure.com/

Kusto cluster urls have "kusto" as part of the url and dont end with ".com" 
please make sure it is right - maybe try also just using the clusters alias if you know it

**Comment by dciborow** [comment]
This is for playfab. They are doing a proxy for the kusto cluster, and therefore the URL does not have kusto in it.

**Comment by dciborow** [comment]
![image](https://user-images.githubusercontent.com/9027725/108125540-9567ed00-7076-11eb-8297-04af9f85eaa8.png)

**Comment by ohadbitt** [comment]
we will have to fix it - either by adding it as a special case (as we do with aria proxy) or by finding a way to deal with proxy cases
Anyway it might take a few days for a fix but we welcome contributions

**Comment by ohadbitt** [comment]
Please use v2.7.1
note that you will have to use the following configuration with the proxy
            option("readMode", 'ForceDistributedMode'). \
              KustoSourceOptions.KUSTO_BLOB_STORAGE_SAS_URL -> containerSas
      //      KustoSourceOptions.KUSTO_BLOB_STORAGE_ACCOUNT_NAME -> storageAccountName,
      //      KustoSourceOptions.KUSTO_BLOB_STORAGE_ACCOUNT_KEY -> blobKey,
      //      KustoSourceOptions.KUSTO_BLOB_CONTAINER -> container

where you can either give a container sas with list read and write permissions or storageAccountName +blobKey+containerName 
as explained here
https://github.com/Azure/azure-kusto-spark/blob/master/docs/KustoSource.md

**Comment by vladikbr** [comment]
Resolved in 2.7.1
