### ISSUE TITLE
evaluate estimate_rows_count() plugin is unsupported

### ISSUE THREAD

**Issue by janak1710** [Azure/azure-kusto-spark#175]
**Describe the bug**
evaluate estimate_rows_count() plugin is unsupported for many data explorer clusters.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16740229/111509089-99d10580-8709-11eb-8760-7a19e5d4570a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by ohadbitt** [comment]
May i ask whats th real issue here,?

**Comment by janak1710** [comment]
After estimate_rows_count doesn't return any results, the spark application just waits for around 4-5 mins and doesn't execute any read operations.

**Comment by ohadbitt** [comment]
Hi the estimation is just a heuristic - the new Kust o engine does not work well with it but it shouldnt impact the performence - if you think there's some other problem please share the spark driver logs for the run (these are log4j where each line starts with KustoConnector)

**Comment by ohadbitt** [comment]
Anyway if you know in advance if you want distributed read or not you can specify it using the option KUSTO_READ_MODE 
https://github.com/Azure/azure-kusto-spark/blob/master/docs/KustoSource.md

**Comment by ohadbitt** [comment]
closed for no response
