### ISSUE TITLE
Syntax error while creating a temp Kusto table

### ISSUE THREAD

**Issue by MinKPark** [Azure/azure-kusto-spark#176]
**Describe the bug**
while saving a dataframe to Kusto in the "append" mode, Kusto connector throws an exception below. 
Caused by: com.microsoft.azure.kusto.data.exceptions.DataWebException: BadRequest_SyntaxError: Request is invalid and cannot be executed.
Syntax error: . Query: '.create table _tmpTableDatabricksShell_AzDUtilization_msu_common_6ec5d478_629f_469f_9783_9fe1d6ae5624 (['string']:ClusterTypeGroup,['string']:Geo,['string']:Region,['real']:TotalUtilization,['long']:TotalActualCapacity,['long']:TotalUsage,['long']:TotalUnusedCapacity,['long']:ReservationNodes,['long']:OutOfRotation,['real']:AverageOfTargetUtilization,['string']:AverageOfDte,['datetime']:LatestNextCapacity,['datetime']:Timestamp,['datetime']:ExtractDT) with(hidden=true)'
Error details:
ClientRequestId='KJC.execute;dec0203c-cdb7-4525-a959-f1a36f126470', ActivityId='a880764e-7dc4-4122-bbe1-7f5a87d2eacc', Timestamp='2021-03-24T21:26:13.8316166Z'.
it looks like that the problem is from the reversed order of column name and column type in the creation script. 
Currently, we are using 1.1.2 and 1.1.6 Kusto connector. 

**Expected behavior**
can create a temp table.

**Screenshots**
![image](https://user-images.githubusercontent.com/8387801/112386094-adeaa900-8cad-11eb-9e69-206862e0ee7b.png)

**Additional context**
Azure databricks 6.4 with Kusto connector 1.1.2/1.1.6
somehow, this problem happens in a specific Kusto cluster.

**Comment by ohadbitt** [comment]
Answered by mail
This is due to a change in some service response. 
Please either upgrade to latest version (2.3.1 or better use the new artifact kusto-spark_2.4_2.11)
If you cannot upgrade please contact us again
