### ISSUE TITLE
Unable to write to ADX Database using Azure Kusto Spark library using version  com.microsoft.azure.kusto:kusto-spark_3.0_2.12:2.3.0 on Databricks cluster

### ISSUE THREAD

**Issue by yokofms** [Azure/azure-kusto-spark#178]
**Describe the bug**

Unable to ingest data into ADX database using Azure Kusto Spark SDK. We currently have a Databricks notebook successfully streaming data to an ADX table. After creating a new cluster the same method no longer works with the exact same data. The error is the following:

Caused by: com.microsoft.azure.kusto.data.exceptions.DataWebException: {
'error': {
'code': 'BadRequest_SyntaxError',
'message': 'Request is invalid and cannot be executed.',
'@type': 'Kusto.Data.Exceptions.SyntaxException',
'@message': 'Syntax error: . Query: '.create table _tmpTableDatabricks_Shell_test_XTOWellsDaily_3eb22cb2_85b3_41d7_a118_6ea476e50276 (['string']:APINumber,['string']:Source,['string']:UniqueTag,['string']:Measurement,['datetime']:RecordDateTimeUTC,['string']:Value,['string']:Unit,['datetime']:RecordAddedUTC) with(hidden=true)'',

The above issue occurs when using com.microsoft.azure.kusto:kusto-spark_3.0_2.12:2.3.0. By using com.microsoft.azure.kusto:kusto-spark_3.0_2.12:2.5.2

**To Reproduce**

Write data to an existing table with the following code: 

writeTable = "test_existing"

(df0
  .write
  .format("com.microsoft.kusto.spark.datasource")
  .option("kustoCluster",sparkKustoOptions_Cluster2["kustoCluster"])
  .option("kustoDatabase",sparkKustoOptions_Cluster2["kustoDatabase"])
  .option("kustoTable", writeTable)
  .option("kustoAadAppId",sparkKustoOptions_Cluster2["kustoAadAppId"])
  .option("kustoAadAppSecret",sparkKustoOptions_Cluster2["kustoAadAppSecret"])
  .option("kustoAadAuthorityID",sparkKustoOptions_Cluster2["kustoAadAuthorityID"])
  .option("tableCreateOptions","CreateIfNotExist")
  .mode("Append")
  .save()
)

**Expected behavior**
com.microsoft.azure.kusto:kusto-spark_3.0_2.12:2.3.0 works for older cluster, hence I would like to understand prerequisite for using com.microsoft.azure.kusto:kusto-spark_3.0_2.12:2.5.2

**Screenshots**

**Desktop (please complete the following information):**
 - OS: n/a.  Databricks Runtime ver 7.6 

**Additional context**

**Comment by ohadbitt** [comment]
Hello
This is a known issue with versions prior to 2.3.1
The service returns now a different response for the certain command we used before. Several clusters were adjusted to return the old response for pipelines not to break. Please use a newer version on the new Spark job

**Comment by yokofms** [comment]
Thank you for your quick response and explanation, Ohad.
