### ISSUE TITLE
ApplicationAccessToken Error / Missing libraries (?)

### ISSUE THREAD

**Issue by victorfuzaro** [Azure/azure-kusto-spark#182]
I am trying to ingest data into Azure Data Explorer through PySpark with PyCharm IDE. However, I am having a lot of problems related to missing libraries when running my code.

According to Azure Data Explorer connector's page, I need to install the connector's jar and the two dependencies jar kusto-ingest and kusto-data. 

After download all these 3 jar's and importing them to PySpark, I can't proceed with my data ingestion, it keeps returning me missing library errors. The first one is the azure-storage lib, then I've installed and imported the jar, it asks for adal4j lib, I do the same and it asks oauth2 lib, then json lib, azure-client-authentication lib, javax mail lib, and so on.

I've installed more than 10 jars and I still can't run this ingestion. Am I doing something wrong?

My PySpark version is 2.4. You can see my code below:

	from pyspark.sql import SparkSession

	spark = SparkSession.builder \
	    .master('local[*]') \
	    .appName("Teste") \
	    .config('spark.jars', 'kusto-spark_2.4_2.11-2.5.2.jar,kusto-data-2.4.1.jar,kusto-ingest-2.4.1.jar,azure-storage-8.3.0.jar,json-20180813.jar,adal4j-1.6.5.jar') \
	    .getOrCreate()

	# loading a test csv file
	df = spark.read.csv('MOCK_DATA.csv', header=True, sep=',')

	df.write.format("com.microsoft.kusto.spark.datasource")\
	  .option("kustoCluster", "myclustername")\
	  .option("kustoDatabase", "mydatabase")\
	  .option("kustoTable", "mytable")\
	  .option("kustoAadAppId", "myappid")\
	  .option("kustoAadAppSecret", "mysecret")\
	  .option("kustoAadAuthorityID", "myautorityid")\
	  .mode("Append")\
	  .save()

**Comment by ohadbitt** [comment]
Hello
Im pretty sure that in order to do local pyspark you will need the uber jar with all its dependencies

**Comment by victorfuzaro** [comment]
> 
> 
> Hello
> Im pretty sure that in order to do local pyspark you will need the uber jar with all its dependencies

Hi ohadbitt, thank you for your reply. What exactly do you mean with "uber jar" and its dependencies? Is there any place where I can get this jar and its dependencies?

**Comment by ohadbitt** [comment]
30 minutes ill send link

**Comment by victorfuzaro** [comment]
> 
> 
> 30 minutes ill send link

Take your time! Thank you so much!

**Comment by ohadbitt** [comment]
https://github.com/Azure/azure-kusto-spark/releases/tag/3.0_2.7.1
this is for spark 3.0

**Comment by victorfuzaro** [comment]
> 
> 
> dowload link: https://github.com/Azure/azure-kusto-spark/releases/download/3.0_2.7.1/kusto-spark_3.0_2.12-2.7.1-jar-with-dependencies.jar
> 
> release: link: https://github.com/Azure/azure-kusto-spark/releases/tag/3.0_2.7.1
> this is for spark 3.0
> This is the only jar you will need for the install
> 
> Please update if this works

It worked! Thank you so much! However, it tooks about 5 minutes to ingest a 1.000 rows csv, is it normal? 

Another question is: my production environment uses a HDInsights spark cluster, the spark version is 2.4. Do you have any spark version 2.4 release jar with dependencies? If not, is there some way that I can build the jar with them?

**Comment by ohadbitt** [comment]
2.4:
https://github.com/Azure/azure-kusto-spark/releases/tag/2.4_v2.7.1

**Comment by victorfuzaro** [comment]
> 
> 
> So 5 minutes is the default aggregation in the service
> read here how to alter it
> https://docs.microsoft.com/azure/data-explorer/kusto/management/batchingpolicy
> https://docs.microsoft.com/azure/data-explorer/kusto/management/batching-policy
> In the context of the connector you will have to change these at the level of the database as the ingestion is done to a table you don't control
> Another option is to use flushImmediatly to avoid any aggregation achieve really low latency but this is less recommended and will come with a great cost(usually nice for debugging)
> 
> 2.4:
> https://github.com/Azure/azure-kusto-spark/releases/tag/2.4_v2.7.1

Thank you so much for providing the complete jar for spark 2.4! However, I've tested it and got the error below:

: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at com.microsoft.kusto.spark.datasink.WriteOptions.<init>(KustoSinkOptions.scala:43)

I tried to search about it and noticed that it is related to the Scala version. Firstly, I was testing locally with Spark 2.4.4 which uses Scala 2.12, then I downgraded to the 2.4.0 version which uses Scala 2.11, thos should have worked because it looks like you have built it on top of Scala 2.11 but got the same error again :(

**Comment by ohadbitt** [comment]
I think this error is related to the fact that WriteOptions is a scala object and therefore does not work from pySpark - please follow the pySpark sample 
https://github.com/Azure/azure-kusto-spark/blob/master/samples/src/main/python/pyKusto.py

**Comment by ohadbitt** [comment]
closing for no response
