### ISSUE TITLE
Maven Repository returns 404 when trying to access latest Spark Kusto Connector

### ISSUE THREAD

**Issue by Ceridan** [Azure/azure-kusto-spark#183]
If we navigate to <https://mvnrepository.com/artifact/com.microsoft.azure.kusto> we will see three `spark-kusto-connector` artifact groups:

![image](https://user-images.githubusercontent.com/408149/116989207-1cbe1780-acda-11eb-88d7-e6cce61d148b.png)

The first one (no. 3) has a link to <https://mvnrepository.com/artifact/com.microsoft.azure.kusto/spark-kusto-connector>. It works correctly, but the latest release was on Feb 16, 2021, and it contains only 2.x versions.

Two following items (no. 4 and 5) both have a link to <https://mvnrepository.com/artifact/com.microsoft.azure.kusto/kusto-spark> and this link is broken, it returns 404. The latest release was a few days ago, looks like there are some routing problems.

**Comment by ohadbitt** [comment]
Hello
We will investigate if this is somehow from our side 
Please use this maven search for now
https://search.maven.org/search?q=Kusto%20spark

**Comment by Ceridan** [comment]
Interesting that the direct maven coordinates work. We are using Databricks and install the connector via `com.microsoft.azure.kusto:kusto-spark_3.0_2.12:2.5.2`.

You may close this issue, I just wanted to let you know that there are some problems in Maven Repository and it can confuse some users.

**Comment by ohadbitt** [comment]
Sent a mail to mvnrepository
Its a broken link - the links are
https://mvnrepository.com/artifact/com.microsoft.azure.kusto/kusto-spark_3.0_2.12
https://mvnrepository.com/artifact/com.microsoft.azure.kusto/kusto-spark_2.4_2.11

**Comment by Ceridan** [comment]
Great, thank you for providing working links!

**Comment by ohadbitt** [comment]
Fixed by the mvn site
