### ISSUE TITLE
IngestPrefix is added twice

### ISSUE THREAD

**Issue by GuntherStruyf** [Azure/azure-kusto-spark#187]
https://github.com/Azure/azure-kusto-spark/blob/4b0c07b23ecc57ea4640730cdf24d7765e41c1ab/connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala#L298-L300

It seems as if the IngestPrefix check is not negated here, the IngestPrefix is added when it is already present. Should it be added at all?
I have a an error where I get:

`AADSTS500011: The resource principal named //ingest-ingest-<cluster>.westeurope.kusto.windows.net was not found`
Note the double "ingest-",  which I suspect is originating from this or something similar.

I'm probably misunderstanding what the EngineUrl is supposed to be.

**Comment by ohadbitt** [comment]
hi 
engine url is without the ingest-
the engine url is used to query and issue commands on tables 
ingest url is used for ingestion

**Comment by GuntherStruyf** [comment]
So then that function (getEngineUrlFromAliasIfNeeded) is wrong? Since it's _adding_ the IngestPrefix, instead of removing it.

**Comment by ohadbitt** [comment]
right

**Comment by ohadbitt** [comment]
for now please remove the "ingest" from the url yourself

**Comment by ohadbitt** [comment]
fixed on version 2.7.4
