### ISSUE TITLE
kusto library has apache log4j dependancy library, which is now having the security breach. Please help us to know is this library is safe enough to consume for adx spark connector

### ISSUE THREAD

**Issue by lohithrvce** [Azure/azure-kusto-spark#213]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ohadbitt** [comment]
The only dependency shows log4j in the dependency:tree print is coming from Spark which is of course under scope - provided .
Therefore if the Spark environment does not use it - nothing is compromised
