### ISSUE TITLE
Kusto query result is not loading correctly in Azure Synapse

### ISSUE THREAD

**Issue by esb797** [Azure/azure-kusto-spark#227]
**Describe the bug**
Kusto query result is not loading correctly in Azure Synapse

**To Reproduce**

Loading in Azure Synapse:
`kustoDf  = spark.read \`
`    .format("com.microsoft.kusto.spark.synapse.datasource") \`
`    .option("spark.synapse.linkedService", <linked service>) \`
`    .option("kustoDatabase", <db name>) \`
`    .option("kustoQuery", "table1 | where DeviceID == 3***2 | limit 100") \`
`    .load()`
This works and loads the data properly.

Kusto query:
`Table1`
`| where DeviceID == 3***2`
`| extend LogDate = todatetime(strcat(substring(TimeStamp, 0, 13), ":00:00"))`
`| summarize MeanValue = avg(todecimal(value)) by LogDate, IndicatorName`
`| evaluate pivot(IndicatorName, sum(MeanValue))`
This query returns the data correctly when executed in ADX.

However, when I tried to load it to Azure Synapse using the more complex Kusto query shown as above, the data is not returned properly:
`kustoDf  = spark.read \`
`    .format("com.microsoft.kusto.spark.synapse.datasource") \`
`    .option("spark.synapse.linkedService", <linked service>) \`
`    .option("kustoDatabase", <db name>) \`
`    .option("kustoQuery", <Kusto query>) \`
`    .load()`
The returned data has zeroes (0E-14) only.

I tried adding a line to the Kusto query as `| render table` and `| project <list of columns>`, but it didn't work.

**Expected behavior**
The data should have non-zero values.

**Comment by ag-ramachandran** [comment]
Hello @esb797, We have some later versions of the connector (where we fixed issues with specific datatypes for example). Is it something you want to try and report if you still face issues with the query

**Comment by ag-ramachandran** [comment]
Newer version of Synapse have been released which have these fixes
