### ISSUE TITLE
PySpark Dates are automatically converted to local timezone

### ISSUE THREAD

**Issue by dciborow** [Azure/azure-kusto-spark#235]
**Describe the bug**
When exporting records to Pyspark, time values are being adjusted for the local timezone, but do not contain the timezone information in the object.

**To Reproduce**

![image](https://user-images.githubusercontent.com/9027725/163031751-b0016194-2338-4ba0-bd4a-eb257fab98a8.png)

**Expected behavior**

In the above query, it is expected that the Year, Month, and Day of Timestamp and Timestamp2 be equal in Python, but, they are not.
![image](https://user-images.githubusercontent.com/9027725/163031787-44a27a5c-b88c-48a1-9ada-7ebe0ca21f3b.png)
By the time the data is loaded into Python, an offset is applied (which seems to be my local timezone vs UTC time, so for me in NYC timezone, all my results are 5 hours to low.

**Screenshots**

**Desktop (please complete the following information):**
- Windows 11
- Python 3.8
- Spark 3.2.1
- kusto-spark_3.0_2.12:2.9.1
- hadoop-azure:3.3.1

**Additional context**
I was able to replace my kusto query "extend" statement with this command in PySpark. This properly loads the date, which is equal to the orginal.

`.withColumn(self.titles.col_date, expr("make_date(year, month, day)"))`

**Comment by dciborow** [comment]
My fix was not complete...
![image](https://user-images.githubusercontent.com/9027725/163085254-513de386-ebd4-4964-866f-99d4b6feace0.png)

Still some weird edge cases to work out...

**Comment by ohadbitt** [comment]
Is this single mode or distributed mode? You can see it from the loga and
read here how to enforce the mode https://github.com/Azure/azure-kusto-spark/blob/master/docs/KustoSource.md

**Comment by dciborow** [comment]
This was in single mode, but was able to reproduce in disturbed as well on Synapse.

**Comment by AsafMah** [comment]
@dciborow 
Could not manage to recreate - I tried with the following:
```python
kustoDf  = pyKusto.read. \
            format("com.microsoft.kusto.spark.datasource"). \
            option("kustoCluster", kustoOptions["kustoCluster"]). \
            option("kustoDatabase", kustoOptions["kustoDatabase"]). \
            option("kustoQuery", "datatable(a:string)[\"3\",\"5\"] | extend TS=make_datetime(2021,05,13)"). \
            option("kustoAadAppId", kustoOptions["kustoAadAppId"]). \
            option("kustoAadAppSecret", kustoOptions["kustoAadAppSecret"]). \
            option("kustoAadAuthorityID", kustoOptions["kustoAadAuthorityID"]). \
            load()

display(kustoDf) 
```
And the dates were UTC, regardless of the python setting.

Can you maybe share the full retrieval code?

Also, when running the query directly in kusto, does it give the answer you want?

**Comment by ohadbitt** [comment]
Closed for no action
