### ISSUE TITLE
Fail the batch if an ingestion times out

### ISSUE THREAD

**Issue by yihezkel** [Azure/azure-kusto-spark#237]
Ingestion currently succeeds if `ingestClient.ingestFromBlob(blobSourceInfo, props)` takes more than 20s (see https://github.com/Azure/azure-kusto-spark/blob/master/connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala#L157 and https://github.com/Azure/azure-kusto-spark/blob/master/connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala#L360).

The ingestion might fail or not completed (especially if the blob doesn’t make it into the same batch as previous blobs), though, which would be ignored by moving to the next stage in what's supposed to be an atomic process - moving the extents from the temp table to the destination table.

This becomes data loss when:
1) The timed-out-then-failed ingestion isn't reported as having failed, or
2) When the not-yet-successful timed out blob eventually proceeds to ingestion, but since the extents were already moved, the temp tables were deleted, deleting the about-to-succeed blob from its source.

We should:
1) Consider raising this timeout we wait for each ingestion, depending on how often this happens. If we do, this will carry a performance penalty in rare circumstances. Fortunately, I believe I’ve identified a performance optimization – I’m no scala expert, but the ingestions do not seem to be done in parallel (https://github.com/Azure/azure-kusto-spark/blob/master/connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala#L157), which seems easily fixable (https://stackoverflow.com/questions/1751953/concurrent-map-foreach-in-scala).
2) Fail the batch if the ingestion didn’t complete successfully in time (i.e. by the timeout).

**Comment by ohadbitt** [comment]
#244
