### ISSUE TITLE
Update azure-kusto-java package to at least 3.1.0 to use HttpClientProperties feature for Kusto Client

### ISSUE THREAD

**Issue by ChingChuan-Chen** [Azure/azure-kusto-spark#238]
**Is your feature request related to a problem? Please describe.**
 azure-kusto-java 3.1.0 provides a feature to configure HttpClientProperties in initializing client which can help to resolve the issue to keep alive for time-consuming commands. 
I have not tried to override version to see whether it's workable to override the package version.

**Describe the solution you'd like**
Update Kusto-SDK version from 2.8.2 to at least 3.1.0.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yihezkel** [comment]
We'll be doing this over the coming days.

**Comment by ohadbitt** [comment]
Update on #242 
But please tell us which long operation do you refer to - as it might have been fixed 
Also you need to configure timeout on ClientRequestProperties to increase operations timeout
