### ISSUE TITLE
Provided samples do not work for Kusto cluster in Synapse workspace

### ISSUE THREAD

**Issue by elenaterenzi** [Azure/azure-kusto-spark#239]
**Describe the bug**
Going through the sample at https://docs.microsoft.com/en-us/azure/data-explorer/spark-connector the provided tutorial assumes that your cluster is **not** a synapse ADX pool, a way to choose whether the ADX pool is a Synapse ADX pool should be provided through the spark kusto connector.

**To Reproduce**
- Create an ADX pool in synapse
- run the sample
- at the first attempt to connect to the ADX pool this error will be thrown:

```
DataServiceException: IOError when trying to retrieve CloudInfo
Caused by: UnknownHostException: <cluster>.kusto.windows.net: Name or service not known
```
> Note that the connector is trying to connect to my ADX cluster using **.kusto.windows.net** instead of **kusto.azuresynapse.net**

**Expected behavior**
The connector should allow for a parameter to dictate whether the ADX cluster is in a synapse workspace or not

**Comment by yihezkel** [comment]
We have documentation for using the Spark Connector with Synapse at https://docs.microsoft.com/azure/synapse-analytics/quickstart-connect-azure-data-explorer

But that's a good point you raised - we'll enrich the main tutorial at the link you included to refer to the link above for Synapse.
