### ISSUE TITLE
Databricks write to Azure Data Explorer writes suddenly become slower

### ISSUE THREAD

**Issue by RengarLee** [Azure/azure-kusto-spark#240]
**Describe the bug**
Now, I write to Azure Data explorer using Spark streaming. one day， writes suddenly become slower. restart is no effect.

**Expected behavior**
There will be no fluctuations in performance 
Why is this happening?
**Screenshots**
Figure 1 shows the performance of writing in the current table.
![Figure1](https://user-images.githubusercontent.com/23287334/171354418-b44cd08a-4eb5-457a-8cf6-78ee6b956ef0.png)
Figure 2 the performance of writing in the now table.
![Figure 2](https://user-images.githubusercontent.com/23287334/171354450-242fda89-a7cb-4781-9df8-bd06596c6758.png)
Figure 3 the performance of writing in the current table, but the checkpoint location is new.
![Figure3](https://user-images.githubusercontent.com/23287334/171354500-fedc6d8c-8bee-4937-b13b-5c9ab8d54ca8.png)

**Desktop (please complete the following information):**
 Databricks Runtime Version:10.4 LTS
azure-cosmos-spark_3-2_2-12:4.9.0

**Comment by ohadbitt** [comment]
This seems like an issue with input rate which is before kusto
Either check the upstream stream 
Or open issue with databricks team

**Comment by RengarLee** [comment]
Thanks @ohadbitt 
Let me add some new information.
Figure 1 shows the Write suddenly slows down
![Snipaste_2022-06-16_09-17-04](https://user-images.githubusercontent.com/23287334/173980034-a4312644-6f91-400b-b150-1b57a124a1df.png)
Figure 2 shows When writing suddenly slows down, the upstream write rate
![image](https://user-images.githubusercontent.com/23287334/173980159-a961765f-0470-4238-80f3-e02d71b806c5.png)
Ingestion Batching Policy of adx is the default setting.

**Comment by yihezkel** [comment]
Hi @RengarLee,

We don't see how this is connected to the Kusto Connector. We suggest narrowing down where the slowdown happens, which seems to be on the Databricks side, in which case it would make most sense to open a ticket to them.
