### ISSUE TITLE
not able to push data into ADX using databricks spark.

### ISSUE THREAD

**Issue by iamrsaravana** [Azure/azure-kusto-spark#241]
**Describe the bug**
i have followed the steps mentioned it below:
1) created table as mentioned it below in My Dataexplor
.create table subscore (subject1 : string, subject2:string, subject3:string)
2) I have create databricks cluster and added the below dependency libraries 

![image](https://user-images.githubusercontent.com/7235459/171841189-6145b09e-524b-4434-b47f-4a1dbd6ba134.png)

3)
%python
import pyspark
from pyspark.sql import SparkSession

# creating sparksession and giving 
# an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list  of college data with two lists
data = [["java", "dbms", "python"], 
        ["OOPS", "SQL", "Machine Learning"]]
  
# giving column names of dataframe
columns = ["Subject 1", "Subject 2", "Subject 3"]
  
# creating a dataframe
dataframe = spark.createDataFrame(data, columns)
  
# show data frame
dataframe.show()

KustoSparkTestAppId = "ba63fxxx-xxxx-xxxx-xxxx-d5b9f9688cdd"
KustoSparkTestAppKey = "1xxxx~xddxxx"

appId = KustoSparkTestAppId
appKey = KustoSparkTestAppKey
authorityId = "02aa9fc1-xxx-xxxx-xxxx-xxxx854dd434" 

dataframe.write. \
  format("com.microsoft.kusto.spark.datasource"). \
  option("kustoCluster", "https://mycluster.kusto.windows.net"). \
  option("kustoDatabase", "xom1database"). \
  option("kustoTable", "subscore"). \
  option("kustoAadAppId", appId). \
  option("kustoAadAppSecret",appKey). \
  option("kustoAadAuthorityID", authorityId). \
  mode("Append"). \
  save()
The below error message I am getting it.
![image](https://user-images.githubusercontent.com/7235459/171841641-c794ffd1-2e3c-4f49-b31b-e2943eccdcdb.png)

**To Reproduce**

**Expected behavior**
two rows should be inserted into table, but it is not happening.

**Screenshots**
![image](https://user-images.githubusercontent.com/7235459/171841685-ae1d7df4-4463-4a29-bf22-acd4b69508b6.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/7235459/171841824-3665bd57-4c43-4c68-a500-2ea7e344b3b6.png)
**Additional context**

**Comment by iamrsaravana** [comment]
Am I missing any libraries here?

**Comment by RengarLee** [comment]
Try it.
![image](https://user-images.githubusercontent.com/23287334/172285327-07431cd1-8cc5-4c86-af43-e572f5726259.png)

**Comment by iamrsaravana** [comment]
Thanks for response Rengar lee. It is working now. but I am getting into another issue, inserting two records It is taking 5 mins

![image](https://user-images.githubusercontent.com/7235459/172313799-be787af3-5534-4ea1-9378-791186afe80d.png)

is it a driver issue or anything we need to configure it?

**Comment by ohadbitt** [comment]
Defaulr kusto batching time is 5 minutes
You should change database batching policy 
https://github.com/Azure/azure-kusto-spark/blob/master/samples/src/main/python/pyKusto.py

Less recommended is to use the flushimmediately flag
https://github.com/Azure/azure-kusto-spark/blob/master/samples/src/main/python/pyKusto.py
Line 85
Setting true for first argument
