### ISSUE TITLE
Kusto Spark classes not available to SparkListener?

### ISSUE THREAD

**Issue by wjohnson** [Azure/azure-kusto-spark#245]
**Describe the bug**

I'm looking to import Kusto Spark inside of a SparkListener context. Unfortunately, I am consistently running into ClassNotFoundException, NoClassDefFoundErrors when either using an import statement or attempting to use a classloader.

```
22/07/09 14:19:55 INFO MyLogger: Trying KustoRelation
22/07/09 14:19:55 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoClassDefFoundError: com/microsoft/kusto/spark/datasource/KustoRelation
	at listener.MyListener.onJobStart(MyListener.java:49)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1599)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: java.lang.ClassNotFoundException: com.microsoft.kusto.spark.datasource.KustoRelation
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 15 more
```

**To Reproduce**

* Construct a Spark Listener
* Try to import a KustoRelation or try to load KustoRelation with a ClassLoader.
* Observe the driver logs which indicates the class was not found.

```
package listener;

import org.apache.spark.scheduler.SparkListenerJobStart;
import com.microsoft.kusto.spark.datasource.KustoRelation;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MyListener extends org.apache.spark.scheduler.SparkListener {

  private static final Logger log = LoggerFactory.getLogger("MyLogger");

  public MyListener() {
    log.info("INITIALIZING");
  }

  @Override
  public void onJobStart(SparkListenerJobStart jobStart) {

    try{
      log.info("Trying KustoRelation with MyListener Class");
      MyListener.class.getClassLoader().loadClass("com.microsoft.kusto.spark.datasource.KustoRelation");
      log.info("Got KustoRelation through MyListener!");
    }
    catch (ClassNotFoundException e){
      log.info("Fell through to an exception for MyListener KustoRelation get");
    }

    try{
      log.info("Trying DefaultSource with MyListener Class");
      MyListener.class.getClassLoader().loadClass("com.microsoft.kusto.spark.datasource.DefaultSource");
      log.info("Got DefaultSource through MyListener!");
    }
    catch (ClassNotFoundException e){
      log.info("Fell through to an exception for MyListener DefaultSource get");
    }

    log.info(String.format("MYLISTENER: ON JOB START FOR JOB#%s", Integer.toString(jobStart.jobId())));
  }

}

```

**Expected behavior**

I would expect that I can load at least one class from the Kusto Spark connector using `SomeClass.class.getClassLoader().loadClass("com.microsoft.kusto.spark.someClass")` to validate that the Kusto Spark connector is installed on the class path.

For example, I can detect the following classes on the classpath on Databricks:
* [LogicalRelation](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/LogicalRelation.scala)
* [BigQueryRelation](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/2b7e31da519bfa3e0af7ace964ea2793fc7f23f5/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/BigQueryRelation.java)

I want to be able to do the same for the [KustoRelation](https://github.com/Azure/azure-kusto-spark/blob/f8c40d6edad3826447c5d0177a6734d8a1bff576/connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala) but it appears to be package private for some reason?  This project is consistent with [EventHubRelation] but inconsistent with the Spark DataSource V1 API version of the [Cosmos DB connector](https://github.com/Azure/azure-cosmosdb-spark/blob/19561f0d42eaa91f9e4793fbdf30b62b22829868/src/main/scala/com/microsoft/azure/cosmosdb/spark/schema/CosmosDBRelation.scala)

**Environment**
 - Databricks Runtime: 9.1 LTS
 - Kusto Connector Version: `com.microsoft.azure.kusto:kusto-spark_3.0_2.12:3.0.0`

**Additional context**

We are working with the [OpenLineage](https://github.com/OpenLineage/OpenLineage) team to extract Kusto Spark lineage out of Databricks and we need to be able to determine if the Kusto Spark Connector is on the class path so that OpenLineage knows whether or not it should check if a given logical plan contains a KustoRelation.

I've attempted to use reflection to check if any of the core classes exist, using a classloader, and using `Class.forName` but nothing seems to work. Any guidance / out of the box thinking would be greatly appreciated!

**Comment by yogilad** [comment]
@ohadbitt , @yihezkel , can one of you have a look?

**Comment by ohadbitt** [comment]
The class you should load is the default source com.microsoft.kusto.spark.datasource.DefaultSource
If its not enough i guess we could make it public 

BTW, It seems like its also private in eventhubs .. https://github.com/Azure/azure-event-hubs-spark/blob/b41c397038f77f2a68105c8b33aa48b2787e25b7/core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsRelation.scala

**Comment by wjohnson** [comment]
> The class you should load is the default source com.microsoft.kusto.spark.datasource.DefaultSource If its not enough i guess we could make it public
> 
> BTW, It seems like its also private in eventhubs .. https://github.com/Azure/azure-event-hubs-spark/blob/b41c397038f77f2a68105c8b33aa48b2787e25b7/core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsRelation.scala

Thank you so much, Ohad!  It looks like this may be an issue on a Java Spark Listener rather than an issue with the access modifiers of the Kusto spark package.  We're not out of the water yet but I'll close the issue her.  Thank you for your willingness to help / make changes to support us!
