### ISSUE TITLE
Timestamps losing precision on import

### ISSUE THREAD

**Issue by IvoMerchiers** [Azure/azure-kusto-spark#266]
**Describe the bug**
When reading timestamps from Kusto into spark (with pyspark), timestamps get rounded to milliseconds, even though they should have microsecond precision.

**To Reproduce**
Example with print, but also happens when actually reading from tables

Run this in pyspark with the correct configuration:
```python
>>> kustoOptions = {
    "kustoCluster": xxx,
    "kustoDatabase": "xxx",
    "kustoAadAppId": xxx,
    "kustoAadAppSecret": xxx,
    "kustoAadAuthorityID": xxx,
}
>>> kustoDf = (
    spark.read.format("com.microsoft.kusto.spark.datasource")
    .options(**kustoOptions)
    .option("kustoQuery", "print datetime(2022-11-11 07:45:20.915245)")
    .load()
)
>>> kustoDf.show(truncate=False)

+-----------------------+
|print_0                |
+-----------------------+
|2022-11-11 07:45:20.915|
+-----------------------+
``` 

**Expected behavior**
I expect the resulting datetime to have the precision until microseconds, `datetime(2022-11-11 07:45:20.915245)`.
This precision is documented on the [spark TimestampType doc page](https://spark.apache.org/docs/3.1.3/api/java/org/apache/spark/sql/types/TimestampType.html).

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Running pyspark on databricks single node cluster, runtime 10.4
- spark version: 3.2.1

**Comment by ag-ramachandran** [comment]
Hello @IvoMerchiers , Sorry for being late on the issue. 

What version of the spark connector are you using. We'll try and replicate this on the latest version and report back findings

**Comment by IvoMerchiers** [comment]
Hi @ag-ramachandran, I've added the spark version to the ticket description.

**Comment by ag-ramachandran** [comment]
Hello @IvoMerchiers, we have just released [3.1.7](https://github.com/Azure/azure-kusto-spark/releases/tag/v3.0_3.1.7). Should be in maven central in a few hours
cc: @asaharn

**Comment by ag-ramachandran** [comment]
Hello @IvoMerchiers, If you've had a chance to test and the behavior is okay can you please close the issue as fixed

**Comment by asaharn** [comment]
Closing it. Feel free to open it if issue persists.
