### ISSUE TITLE
 java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by charlesb** [Azure/azure-kusto-spark#273]
When querying a table that contains a **real** data type column, the connector returns this exception: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double

**Comment by ag-ramachandran** [comment]
Hello @charlesb, Thanks for reporting the bug. Couple of questions
a) What version of the connector are you using
b) As I understand, you have a real data-type column that you are selecting as is, without any transform operation. Is that a right understanding?

**Comment by charlesb** [comment]
Workaround is to explicitly cast the real type column to int: project toint(real_type_column)

**Comment by charlesb** [comment]
It only fails when access log analytics workspaces

**Comment by ag-ramachandran** [comment]
Hello @charlesb , we have just released [3.1.7](https://github.com/Azure/azure-kusto-spark/releases/tag/v3.0_3.1.7). Should be in maven central in a few hours
cc: @asaharn @ohadbitt
