### ISSUE TITLE
Unable to execute df.action in synapse.

### ISSUE THREAD

**Issue by msft33333** [Azure/azure-kusto-spark#282]
**Describe the bug**
Our team use synapse to do some daily data aggregation jobs.I tried to get some data from XXX_MV table, and mark their count as log.Here comes the problem.It said:
```
 Fail to run _MYJOB_, exception:
Traceback (most recent call last):
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/usage_ml/jobs/base_job.py", line 65, in run
    self.execute()
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/usage_ml/jobs/_MYJOB_.py", line 127, in execute
    result_df = self.aggregate_user_session_record_df()
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/usage_ml/jobs/aggregate_user_session_data.py", line 59, in aggregate_user_session_record_df
    ("kusto_df", kusto_df.count()))
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 680, in count
    return int(self._jdf.count())
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o297.count.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 15.0 failed 4 times, most recent failure: Lost task 0.3 in stage 15.0 (TID 127) (vm-4d717972 executor 1): java.lang.UnsupportedOperationException: Unsupported encoding: DELTA_BYTE_ARRAY
```
And we tried to save the raw df comes from kusto, also have the same problem.Seems all df action have been blocked due to the issue.
```
 File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o399.save.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 26.0 failed 4 times, most recent failure: Lost task 0.3 in stage 26.0 (TID 152) (vm-cee07706 executor 2): java.lang.UnsupportedOperationException: Unsupported encoding: DELTA_BYTE_ARRAY
```
We use the following code to load data from kusto:
```
    def query_from_kusto(self, kusto_query):
        return self.spark.read \
            .format(self.source_format) \
            .option("spark.synapse.linkedService", self.linked_service) \
            .option("kustoDatabase", self.kusto_db) \
            .option("kustoQuery", kusto_query) \
            .option("authType", "LS") \
            .load()
```

About the version:
![image](https://user-images.githubusercontent.com/122989818/213190319-c155a807-d28c-4885-80ce-8bd77c11960a.png)
But when I use the 3.3 spark pool, the program works fine.
**To Reproduce**
No sure how to reproduce it.We tried to query multiple MV table that contains more than 100000 records and get their df to do action, same problem occured.

**Expected behavior**
Expected to get the df count.

**Screenshots**

**Desktop (please complete the following information):**
I guess in server?
**Additional context**
The kql I used to get the df is like:
```
XXX_MV
        | where Status contains "AAA"
        | distinct UserId,TenantId
```
It would have problem.
But when it goes to:
```
XXX_MV
        | where Status contains "AAA"
        | project TenantId
```
Same size of return records,but it won't have problem.
I also validate the correctness of UserId,all UserId matches regex "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

**Comment by ag-ramachandran** [comment]
Hello @msft33333 
Apologies for this inconvenience, this is a known issue because a new native implementation of Parquet writer that uses new encoding schemes was rolled out on the ADX side. This uses delta byte array for strings and other byte array-based Parquet types (default in Parquet V2 which most modern parquet readers support by default)

Spark 2.x has the issue (with Delta encodings on Parquet V2) as mentioned here https://issues.apache.org/jira/si/jira.issueviews:issue-html/SPARK-26509/SPARK-26509.html

Parquet V2 which has Delta encodings was to be an improvement over the Parquet V1 (plain encoding). Based on documentation, delta encoding provided advantages in reading rows in batches (Ref : https://issues.apache.org/jira/browse/SPARK-12854). These flags are provided as workaround as you can see in the previous ticket on Spark Jira

Mitigation: To mitigate this a new version of the library has been rolled out that will be deployed on Synapse (Spark library version 3.1.10). 

Will triage it to the right team and get you a roll out as soon as possible

Once again apologize for the inconvenience

**Comment by ag-ramachandran** [comment]
Also, to overcome this you can try setting the following spark options and this should fix the issue immediately. We will work parallelly  to get a new revision to Synapse

spark.conf.set("spark.sql.parquet.enableVectorizedReader", "false")
spark.conf.set("parquet.split.files", "false")

**Comment by msft33333** [comment]
Hi @ag-ramachandran ,
Thanks for the detailed reply!The workaround works fine for me,thanks again!

**Comment by msft33333** [comment]
Hi @ag-ramachandran ,
Thanks for the detailed reply!The workaround works fine for me,thanks again!

**Comment by ag-ramachandran** [comment]
Glad that helped @msft33333. If this works can we close the issue
