### ISSUE TITLE
Can read ADX (free tier) from Databricks but cannot write rows to ADX

### ISSUE THREAD

**Issue by hkelley** [Azure/azure-kusto-spark#292]
**Describe the bug**
I am experimenting with ADX/Kusto using a free tier cluster.   My authentication and read commands work quickly but the write command runs for days without sending any rows.    The table is created in the Kusto DB.

**To Reproduce**
Run the Databricks notebook below

```
import org.apache.spark.sql
//import org.apache.spark.sql.{SaveMode, SparkSession}
//import org.apache.spark.sql.types.{StringType, StructType}

import com.microsoft.kusto.spark.datasource.{KustoSourceOptions}
import com.microsoft.kusto.spark.sql.extension.SparkExtension.DataFrameReaderExtension
import com.microsoft.kusto.spark.utils.{KustoDataSourceUtils => KDSU}

KDSU.setLoggingLevel("all")


val cluster = ""
val tenant = "";


//
// Authenticate
val deviceAuth = new com.microsoft.kusto.spark.authentication.DeviceAuthentication(cluster, tenant);

deviceAuth.getDeviceCodeMessage;

val token = deviceAuth.acquireToken();


// Verify connectivity
val database = "CSF"
val table = "junk"

val conf: Map[String, String] = Map(
      KustoSourceOptions.KUSTO_ACCESS_TOKEN -> token
    )

val query = "junk | where autonomous_system_organization startswith \"c\""
spark.read.kusto( cluster, database, query, conf)
  .show();


//
//  Select a few rows to send to ADX
val tableNamePR2 = "ProcessRollup2";

val df  = spark.sql(s"""
  SELECT * 
  FROM silver.$tableNamePR2
  WHERE event_date BETWEEN '2023-01-26' AND '2023-01-27'
  LIMIT 10
""");

df.count();


df.write
  .format("com.microsoft.kusto.spark.datasource")
  .option("kustoCluster", cluster)
  .option("kustoDatabase", database)
  .option("kustoTable", tableNamePR2)
  .option("accessToken", token)
  .option("tableCreateOptions","CreateIfNotExist")
  .mode("Append")
  .save();

```

**Expected behavior**
Rows to be written to Kusto cluster's DB

**Screenshots**

![image](https://user-images.githubusercontent.com/8828244/222419455-47bc01be-d4a3-4165-9f08-83e1ce1f1620.png)

**Desktop (please complete the following information):**
 - Databricks cluster,  personal mode,  12.1 ML (includes Apache Spark 3.3.1, Scala 2.12)
 - com.microsoft.azure.kusto:kusto-spark_3.0_2.12:3.1.11

**Additional context**
I am new to ADX so this may be a rookie error or a limitation of the ADX free tier.
https://learn.microsoft.com/en-us/azure/data-explorer/start-for-free

**Comment by AsafMah** [comment]
We need more details - Are there any errors raised?

Run ".show ingestion failures" on your cluster and see if errors pop up.

Also, the default ingestion policy batches the data for a few minutes before ingesting it and the connector waits for the ingestion to complete (by default).
Try running it with a shorter ingestion batching policy - https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/batchingpolicy

**Comment by hkelley** [comment]
Thank you for the troubleshooting steps.  Apparently this is a resource issue on the free tier ADX. 

```
The cluster has reached its full data capacity of 10,468,982,784 bytes, to ingest more data please reduce the data size by either deleting some of the data or adjusting the retention policy.
```
I thought (based on [this page](https://learn.microsoft.com/en-us/azure/data-explorer/start-for-free)) that the limit was 100 GB,  but in any case, the issue is not with the connector.

I appreciate the guidance on the batching too.

**Comment by ohadbitt** [comment]
One thing that can be related to the connector and if your cluster is low on resources its worth considering - the connector can create leftovers which are supposed to be cleaned at the end of each run - if not they are auto-cleaned by the service after a week (this can happen if a 'write' run is canceled before fully waited). Read here about stagingResourcesAutoCleanupTimeout
https://github.com/Azure/azure-kusto-spark/blob/master/docs/KustoSink.md

This cannot happen in the connector 'Queued' mode.

**Comment by hkelley** [comment]
Would this be the "on demand" equivalent of the staging resources auto cleanup?  This seems to trigger an `IndependentGarbageCollectionRequested` in the cluster.

```
.clean databases extentcontainers
```
