### ISSUE TITLE
Error using Service Principal with Certificate

### ISSUE THREAD

**Issue by vsaroopchand** [Azure/azure-kusto-spark#309]
**Describe the bug**
Currently facing an issue writing to Kusto using Service Principal & Certificate. As you can see in the Linked Service setup below, the connection is successful using Test Connection. However, when writing to the Kusto cluster using AuthType LS it fails with the below error. What am I missing?

**Setup:**

![image](https://user-images.githubusercontent.com/13750198/236864085-76505b81-7ff5-4cd3-a903-dae4476d8f68.png)

**Script:**
df.write \
    .format("com.microsoft.kusto.spark.synapse.datasource") \
    .option("spark.synapse.linkedService", "MyKustoLinkService") \
    .option("kustoDatabase", "MyDb") \
    .option("kustoTable", "MyTestTable") \
    .option("authType", "LS") \
    .mode("Append") \
    .save()

**Error:**
Py4JJavaError: An error occurred while calling o3933.save. : com.microsoft.azure.synapse.tokenlibrary.TokenLibrary$NonRetryableStatusException$1: POST failed with 'Bad Request' (400) and message: {"result":"DependencyError","errorId":"BadRequest","errorMessage":"[Code=, Target=, Message=]. TraceId : 5600b743-ee2b-4435-8309-9fbffbdd98e0 | client-request-id : 40bae8f4-12ed-4ac6-ae19-0e55867036fa. Error Component : LSR"} at com.microsoft.azure.synapse.tokenlibrary.TokenLibrary.$anonfun$invokeTokenService$7(TokenLibrary.scala:470) at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1808) at com.twitter.util.Promise$FutureTransformer.liftedTree1$1(Promise.scala:240) at com.twitter.util.Promise$FutureTransformer.k(Promise.scala:240) at com.twitter.util.Promise$Transformer.apply(Promise.scala:215) at com.twitter.util.Promise$WaitQueue.com$twitter$util$Promise$WaitQueue$$run(Promise.scala:91)

**To Reproduce**
Setup a link service to a Kusto cluster using Service Principal w/ Certificate from a Key Vault.

**Expected behavior**
Dataframe is successfully written to the Kusto Table.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by vsaroopchand** [comment]
Thank you @ag-ramachandran - can you provide more context on the first workaround "Easiest is to use AAD app based auth in the LinkedService, this will work."

**Comment by AnalyticJeremy** [comment]
Leaving a note here for others who are trying to Bing/Google a solution to this problem...

Our team was faced with the same issue.  We wanted to use the Kusto Connector for Spark in Synapse and authenticate with a certificate.  This is the solution we came up with:

```python
import base64
from azure.identity import CertificateCredential

# Get certificate data from Key Vault using the Synapse Linked Service
certificate_data = mssparkutils.credentials.getSecretWithLS("<your-akv-linked-service-name>", "<your-certificate-name-in-akv>")

# Decode the certificate data into bytes (as required by the azure.identity package)
pkcs12_bytes = base64.b64decode(certificate_data)

# Use the certificate bytes to get a credential
credential = CertificateCredential(tenant_id="<your-entra-tenant-id>", client_id="<your-client-id>", certificate_data=pkcs12_bytes, send_certificate_chain=True)

# Get a token for the credential (using Kusto as the scope)
access_token = credential.get_token("https://kusto.kusto.windows.net/.default")

# Use our token to authenticate to Kusto
df = spark.read \
        .format("com.microsoft.kusto.spark.synapse.datasource") \
        .option("accessToken", access_token.token) \
        .option("kustoCluster", "https://<your-cluster-name>.kusto.windows.net") \
        .option("kustoDatabase", "<your-database-name>") \
        .option("kustoQuery", "<your-kql-query>") \
        .load()

display(df)
```
