### ISSUE TITLE
Unable to use connector if uri ends with kusto.fabric.microsoft.com

### ISSUE THREAD

**Issue by ravikiransharvirala** [Azure/azure-kusto-spark#323]
Thank you so much @ag-ramachandran 

I have one more question regarding the connector. 

- I'm able to use the connector to ingest data and query it when my Kusto uri ends with **<region>.kusto.windows.net**. But I get a below error when I use a cluster with uri that ends  **z2.kusto.fabric.microsoft.com**

`Py4JJavaError: An error occurred while calling o1338.load. : com.microsoft.azure.kusto.data.exceptions.DataClientException: $$ALERT[ValidateHostnameIsTrusted]: Can't communicate with '<cluster-name>.z2.kusto.fabric.microsoft.com' as this hostname is currently not trusted; please see https://aka.ms/kustotrustedendpoints`

Could you please help me with this issue?

(_Apologies for re-opening this case even though it's not related to original question_)

_Originally posted by @ravikiransharvirala in https://github.com/Azure/azure-kusto-spark/issues/322#issuecomment-1594042935_

**Comment by ravikiransharvirala** [comment]
This is resolved by updating the connector to latest version.

**Comment by ag-ramachandran** [comment]
Thanks @ravikiransharvirala, happy to help further. Will make the README explicit as well. Thanks once again for the feedback
