### ISSUE TITLE
Write to Kusto in Synapse with option "sparkIngestionPropertiesJson" always failed in spark 3.3

### ISSUE THREAD

**Issue by xiaoshiyi123** [Azure/azure-kusto-spark#342]
**Describe the bug**
Hi Team
   We want to update the Spark pool from 3.2 to 3.3. But when we use "sparkIngestionPropertiesJson" to write to Kusto, the spark job will not stop or fail, running for a long time.
   

**To Reproduce**
1. Create a spark pool with spark 3.3
2. Create a notebook and use this spark pool
3. Read a df and write to Kusto with option "sparkIngestionPropertiesJson"

**Expected behavior**
Write to Kusto successfully.

**Screenshots**
use sp
![image](https://github.com/Azure/azure-kusto-spark/assets/36906182/437bb828-9de4-4a31-9a24-a338aeb33b00)
![image](https://github.com/Azure/azure-kusto-spark/assets/36906182/eef77970-44a4-46ea-9d7b-509d17019671)

do not use sp can success
![image](https://github.com/Azure/azure-kusto-spark/assets/36906182/b4cb1b47-e7f2-4259-a7d9-ab9417fdc4fc)

**Desktop (please complete the following information):**
![image](https://github.com/Azure/azure-kusto-spark/assets/36906182/c86733d2-fa64-455b-a458-a285e668c1dc)

**Additional context**

**Comment by ag-ramachandran** [comment]
Hi @xiaoshiyi123 

a) There are a couple of challenges here,  by using SparkIngestionPropertiesJson, we are using the FlushImmediatelt flag to true, which we do not recommend.

 Here is how the internals work
 
DataFrame ----> Write to blob ------> Ingest this blob
 
To optimize for throughput in ingestion, the size of the blob is critical. Kusto is optimized for few large blobs , as opposed to many small blobs. Please use the right batching policy from Kusto and you can get rid of SparkIngestionProperties altogether

(Refer : https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/batchingpolicy)
 
 b) You can try and use the Queued writeMode, IIRC right the version in Synapse had an issue that where the shards that were to be merged were queried incorrectly (so probably that could be a cause too)
If you still want to use the FlushImmediately flag still (Not recommended, will result in no aggregation and many smaller ingestion, please use the queued write option  

.option("writeMode","Queued")

Refer : https://github.com/Azure/azure-kusto-spark/blob/master/docs/KustoSink.md writeMode

**Comment by xiaoshiyi123** [comment]
Thanks @ag-ramachandran 
.option("writeMode","Queued") solved my problem.
Thanks for your kind answer and suggestions.
