### ISSUE TITLE
Dependency issues after update to maven kusto-spark_3.0_2.12:5.0.7

### ISSUE THREAD

**Issue by LHERMELB** [Azure/azure-kusto-spark#381]
**Describe the bug**
Connector of updating from 3.0_2.12:5.0.6 to maven 3.0_2.12:5.0.7 not working anymore. msal installed before, msal4j requested after update. After installing msal4j writing data worked, but reading still not worked. Installing of jar instead of maven fixed the problem as a workaround.

**To Reproduce**
Could be reproduced by Microsoft support, TrackingID#2406050050003680

**Expected behavior**
Connector working independing how it is installed

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by LHERMELB** [comment]
Installing from com.microsoft.azure.kusto:kusto-spark_3.0_2.12:5.0.7 plus com.azure:azure-identity:1.10.4 library from maven solved the problem.

**Comment by ag-ramachandran** [comment]
Hello @LHERMELB , 5.0.8 is released with this fix : https://mvnrepository.com/artifact/com.microsoft.azure.kusto/kusto-spark_3.0_2.12/5.0.8

You can try it too without adding dependencies
