### ISSUE TITLE
[DATA_SOURCE_NOT_FOUND] Failed to find the data source: com.microsoft.kusto.spark.synapse.datasource.

### ISSUE THREAD

**Issue by bingqiangxiang** [Azure/azure-kusto-spark#413]
I have introduced the latest package into my pom.xml, but I still got the exception. 

![Image](https://github.com/user-attachments/assets/9fb2fdaa-99be-4ec5-b3e6-3aea0c173a7d)

![Image](https://github.com/user-attachments/assets/0b6d58c7-9178-4417-8ec3-194bc45776a3)

Below is how I connect to my kusto cluster, is there any other possibility to cause such issues?

![Image](https://github.com/user-attachments/assets/51bc77c4-3e8d-420d-af0a-d3d42f2f5f8d)

**Comment by ag-ramachandran** [comment]
hello @bingqiangxiang , are you running on Synapse Spark ? What is your spark runtime.

From the usage of pom.xml, I assume it is not synapse spark perhaps ?

You will have to use **.format("com.microsoft.kusto.spark.datasource")** and not the synapse datasource.

The samples are at : https://github.com/Azure/azure-kusto-spark/tree/master/samples/src/main/scala , please do have a look and see if this helps

**Comment by bingqiangxiang** [comment]
@ag-ramachandran  oh, right. It should be **com.microsoft.kusto.spark.datasource**, thanks
