### ISSUE TITLE
Read not working java.lang.NoClassDefFoundError: com/microsoft/azure/kusto/data/ConnectionStringBuilder

### ISSUE THREAD

**Issue by omkar9194** [Azure/azure-kusto-spark#42]
While reading using the beta-02 connector, 
always getting this error :- java.lang.NoClassDefFoundError: com/microsoft/azure/kusto/data/ConnectionStringBuilder

Getting this error on both python, scala  in databricks.
Python ->3 ; Scala 2.11 ; Databricks -> 5.0

from pyspark.sql import SparkSession
pyKusto = SparkSession.builder.appName("kustoPySpark").getOrCreate()

kustoDf  = pyKusto.read. \
            format("com.microsoft.kusto.spark.datasource"). \
            option("kustoCluster", kustoOptions["kustoCluster"]). \
            option("kustoDatabase", kustoOptions["kustoDatabase"]). \
            option("kustoQuery", query). \
            option("kustoAADClientID", kustoOptions["kustoAADClientID"]). \
            option("kustoAADAuthorityID", kustoOptions["kustoAADAuthorityID"]). \
            option("kustoClientAADClientPassword", 
             kustoOptions["kustoClientAADClientPassword"]). \
            option("readMode", "lean"). \
            load()

**Comment by michazag** [comment]
Hi Omkar,

Here is from the connector README.md<https://github.com/Azure/azure-kusto-spark/blob/dev/README.md>, I think this is the missing part:
Dependencies
Spark Kusto connector takes dependency on Kusto Data Client Library<https://mvnrepository.com/artifact/com.microsoft.azure.kusto/kusto-data> and Kusto Ingest Client Library<https://mvnrepository.com/artifact/com.microsoft.azure.kusto/kusto-ingest>, available on maven repository. When Key Vault based authentication<file:///C:/GitHub/azure-kusto-spark/Authentication.md> is used, there is an additional dependency on Microsoft Azure SDK For Key Vault<https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault>.
Note: When working with Databricks, Kusto connector requires Kusto java client libraries (and azure key-vault library if used) to be installed. This can be done by accessing Databricks Create Library -> Maven -> Search Packages (Maven Central)

**Comment by omkar9194** [comment]
Thanks Michael!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
