### ISSUE TITLE
Abilty to specify blob storage account on SPARK ingestion

### ISSUE THREAD

**Issue by pvchandu** [Azure/azure-kusto-spark#82]
As I can specify my blob storage on reads, can I specify, my storage account on write to kusto as well. That way, I have control over my data and can use it for further purposes if necessary.

Ex: I can have a retention policy of 30 days in Kusto, while the data still can sit in the blob storage.

**Comment by ohadbitt** [comment]
Hi,
After discussing your suggesting we decided not to support choosing the storage account for writing. 
Spark connector is not intended for ingesting blobs you already have, if you want to ingest from an existing blob please use any other kusto sdk, such as the java sdk that the connector already reference to - https://github.com/Azure/azure-kusto-java/blob/427a19247be4795bf4281eded60f8d9b48b6bad1/ingest/src/main/java/com/microsoft/azure/kusto/ingest/IngestClient.java

One reason that the blob storage isn't configurable for cases you need to ingest from a spark dataframe is that the files created by the connector are staging files used just for the ingestion and are under the ownership of kusto, so kusto can control the ingestion traffic.  Note - Staging blobs are deleted efficiently once a week.

If you want you can export the data back to blob storage using kusto export command.

The option to indicate blob storage is scheduled to be deleted too.
