### ISSUE TITLE
Ability to write to file format of my choice other than csv while ingestion

### ISSUE THREAD

**Issue by pvchandu** [Azure/azure-kusto-spark#83]
While writing the data to Kusto, I guess the SPARK Connector is writing to blob storage account in csv format. The problem I have with this is that my data can contain new lines or any such format that can break csv. I need an ability to specify the format (Ex: json.gz or tsv.gz or avro.gz) here.

**Comment by ohadbitt** [comment]
Hi,
After discussing your suggesting we decided not to support altering the file format as this is an intermediate file created just for the ingestion and is saved in the most efficient format for Kusto ingestions. New lines will work well in our next version as we discarded the CsvWriter that was used and replaced it with our own implementation where now all strings will be closed between two quotation marks - "<string-value>". Sorry for the inconvenience.
