### ISSUE TITLE
Alter the table schema if it exists 

### ISSUE THREAD

**Issue by pvchandu** [Azure/azure-kusto-spark#84]
Schema of my table might change, and I want to handle the schema changes while we ingest data from SPARK. I need an ability to Alter the table schema if it exists i.e. create-merge if a table exists.

**Comment by ohadbitt** [comment]
Hi,
After discussing your suggesting we decided not to support altering the table schema automatically by the connector as this can lead to mistakes that can have great impact (especially when dropping columns which lead to data loss) and might fail subsequent ingestions.
This can be done by the user by any sdk, the java sdk is already referenced to by the connector.
https://github.com/Azure/azure-kusto-java/blob/master/samples/src/main/java/Query.java
