### ISSUE TITLE
Error in creating application access token

### ISSUE THREAD

**Issue by anshu007** [Azure/azure-kusto-spark#90]
I am trying to migrate data from lake to data explorer using spark job,but I am getting token issue.

val cluster = "xxx"
val database = "xxx"
val table = "xxx"
val authorityId = "xxx" 

import com.microsoft.kusto.spark.datasink.SparkIngestionProperties
import com.microsoft.kusto.spark.sql.extension.SparkExtension._
import com.microsoft.kusto.spark.datasink.KustoSinkOptions

val str="select * from xxx"
val df = spark.sqlContext.sql(str)
val conf = Map(
        KustoSinkOptions.KUSTO_CLUSTER -> cluster,
        KustoSinkOptions.KUSTO_TABLE -> table,
        KustoSinkOptions.KUSTO_DATABASE -> database,
        KustoSinkOptions.KUSTO_AAD_CLIENT_ID -> appId,
        KustoSinkOptions.KUSTO_AAD_CLIENT_PASSWORD -> appKey,
        KustoSinkOptions.KUSTO_AAD_AUTHORITY_ID -> authorityId)
     val sparkIngestionProperties = Some(new SparkIngestionProperties()) // Optional, use None if not needed
     df.write.kusto(cluster, database, table, conf, sparkIngestionProperties)

**Comment by ohadbitt** [comment]
Hi
Please add thw full error you got
Please make sure that the cluater has the region as in "alias.westus" and that the application has sufficient previlages

**Comment by ohadbitt** [comment]
Closed for the client resolved it as an authentication issue in his side.
